apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: central-app-of-apps
  namespace: argocd
  annotations:
    jaytest: "test"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps-jay
    repoURL: https://github.com/StyleTang/argocd-example-apps.git
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
