apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: one-backend-app-jay2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/StyleTang/argocd-example-apps.git
    targetRevision: master
    path: guestbook
    helm:
      releaseName: 'jay2test'
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
